# https://stackoverflow.com/a/53077616/12958126

version: 0.2

env:
  variables:
    remote_origin: "https://github.com/Play-The-World/kr.playtheworld.rails.api.base.git"
    RAILS_ENV: "production"
    RACK_ENV: "production"
  parameter_store:
    git_token: "git_token"

phases:
  install:
    runtime-versions:
      docker: 19
      ruby: 2.7.0
    commands:
      - git config --global url."https://${git_token}:@github.com/".insteadOf "https://github.com/"
      # Check for a .git directory to determine if we need to set up our git package
      - |
        if [ ! -d ".git" ]; then
          git init                                              # Initialize Git
          git remote add origin "$remote_origin"                # Add the remote origin so we can fetch
          git fetch                                             # Get all the things
          git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"  # Checkout the specific commit we are building
        fi
      # Now that setup is complete, get submodules
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
      - echo Logging in to Amazon ECR.... 
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=947202957156.dkr.ecr.ap-northeast-2.amazonaws.com/playtheworld/test-api
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - Dockerrun.aws.json