# https://stackoverflow.com/a/53077616/12958126

version: 0.2

env:
  variables:
    remote_origin: "https://github.com/Play-The-World/kr.playtheworld.rails.api.base.git"
    RAILS_ENV: "production"
    RACK_ENV: "production"
    git_token: "8bc2db5d30945e3c4e0a19fdc65333980d57f574"
    aws_default_region: "ap-northeast-2"
    aws_account_id: "947202957156"
    image_repo_name: "playtheworld/test-api"

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - git config --global url."https://${git_token}:@github.com/".insteadOf "https://github.com/"
      # Check for a .git directory to determine if we need to set up our git package
      - git init                                              # Initialize Git
      - git remote add origin "$remote_origin"                # Add the remote origin so we can fetch
      - git fetch                                             # Get all the things
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"  # Checkout the specific commit we are building
      # Now that setup is complete, get submodules
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
      - echo Logging in to Amazon ECR.... 
      - aws --version
      - $(aws ecr get-login --no-include-email --region $aws_default_region)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=$aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/$image_repo_name
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - Dockerrun.aws.json