version: '3'

services:
  app:
    image: 947202957156.dkr.ecr.ap-northeast-2.amazonaws.com/playtheworld/api
    restart: always
    depends_on: 
      - db
    entrypoint: ./start-up.sh
    environment:
      DB_USERNAME: playtheworld
      DB_PASSWORD: Rhemspdla1!
      DB_DATABASE: new_production
      DB_PORT: 3306
      DB_HOST: playtheworld-main.cluster-cfmnnfrjqm0a.ap-northeast-2.rds.amazonaws.com
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      RAILS_MASTER_KEY: b5eaa4ed133ad1e8cb94bdee99823ae3
    volumes:
      - ${EB_LOG_BASE_DIR}/app:/app/log
  
  nginx:
    image: 947202957156.dkr.ecr.ap-northeast-2.amazonaws.com/playtheworld/nginx:api
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${EB_LOG_BASE_DIR}/nginx:/var/log/nginx
    links:
      - app